mutation addUser($name: String!) {
  addUser(name: $name) {
    id
  }
}

mutation updateUser($id: ID!, $name: String!) {
  updateUser(id: $id, name: $name) {
    id
  }
}

mutation deleteUser($id: ID!) {
  deleteUser(id: $id) {
    id
  }
}
